name: setup webserver with vhost
  hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: install services
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: document root exist
      ansible.builtin.file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
        setype: "httpd_sys_content_t"

    - name: setup Apache virtualhost
      ansible.builtin.template:
        src: "templates/httpd.conf.j2"
        dest: "/etc/httpd/conf.d/{{ http_conf }}"

    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: restarted

    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true

    - name: MySQL - Update mysql root passwd
      mysql_user:
        name: root 
        password: "{{mysql_root_new_pass}}"
        login_user: root
        login_password: "root"
    
    - name: create mysql db
      mysql_db: name=prueba state=present login_user=root login_password="root"
      
    - name: sql db
      mysql_db: name=prueba state=import target=/var/dump/MyDb.sql login_user=root login_password="root"
    
    - name: Configure ufw rules
      ufw: 
        rule: allow 
        port: {{ http_port }} 
        proto: tcp

  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: reloaded

    - name: Restart apache
      service:
        name: apache2
        state: restarted